### ISSUE TITLE
Expose the P2 functionality to the sandbox

### ISSUE THREAD

**Issue by trink** [mozilla-services/lua_sandbox_extensions#117]
https://github.com/mozilla-services/lua_sandbox/issues/193

**Comment by trink** [comment]
This will not be added directly to the lua_sandbox_extensions repo instead it will be setup as an example external module

**Comment by champtar** [comment]
Hi @trink,
Maybe you can have 1 contrib repo where you just merge external modules without full testing. This allow to have only one place to look for but you can disable bug tracker on this repo and add a disclaimer in the readme stating that there is no "support"?

**Comment by trink** [comment]
There has been a lot of discussion around this with no ideal solution. It is looking like independent repos will be the best in the long run and for discoverability we will make it easy for them to be tied into the main documentation.

**Comment by trink** [comment]
https://github.com/trink/streaming_algorithms
