### ISSUE TITLE
HTTP request_method parser is too restrictive in lpeg/common_log_format

### ISSUE THREAD

**Issue by fvanniere** [mozilla-services/lua_sandbox_extensions#121]
In the grammar for common_log_format, request_method is restricted to `GET/POST/HEAD/PUT/DELETE/OPTIONS/TRACE/CONNECT`. These are mandatory supported method for HTTP server but a method can be any token. 

Nginx restricts method to `A-Z` range plus `_` and Apache allows any case sensitive token with methods registered by `Script` (mod_action).

Given RFC 7230 section 3.2.6, request_method should be `(l.alnum + l.S"!#$%&'*+-.^_`|~")^1`

**Comment by trink** [comment]
Thanks
