### ISSUE TITLE
Migrate the documentation to gitbook

### ISSUE THREAD

**Issue by trink** [mozilla-services/lua_sandbox_extensions#129]

**Comment by trink** [comment]
https://people-mozilla.org/~mtrinkala/_book/

Not loving it and it is an order of magnitude slower to generate.  Maybe I should just fix up the TOC (collapsible/scroll-able with a DuckDuckGo site search)

Opinions?

**Comment by bbinet** [comment]
This is completely subjective, but I like gitbook output.

**Comment by trink** [comment]
I got more feedback offline: people seem to like the gitbook output, it will match our telemetry docs,  it is easier for me and it will not be hard to change in the future.

https://mozilla-services.github.io/lua_sandbox_extensions/
