### ISSUE TITLE
Broken lpeg Debian package

### ISSUE THREAD

**Issue by deric** [mozilla-services/lua_sandbox_extensions#149]
Latest version from git contains invalid meta information in Debian package `luasandbox-lpeg-1.0.5-Linux.deb `:
```
 Package: luasandbox-lpeg
 Version: 1.0.5
 Section: devel
 Priority: optional
 Architecture: amd64
 Depends: , luasandbox (>= 1.0.2) 
```

**Comment by trink** [comment]
https://github.com/mozilla-services/lua_sandbox_extensions/commit/d110e106da1016760902f552537892c51f589736
