### ISSUE TITLE
Cannot decode syslog message

### ISSUE THREAD

**Issue by cvuillemez** [mozilla-services/lua_sandbox_extensions#173]
Hi,
not sure if it's a configuration mistake from me, but I can't have the syslog extension working with a simple message.

Here is the TCP payload sent to my Hindsight instance:

`echo -n '<13>2017-10-16T15:00:47.812399+02:00 foo bar: dummy_message' | nc -q0 localhost 5566`

And the configuration files:

- `run/input/syslog_tcp.cfg:`

```
filename = "tcp.lua"
address = "*"
decoder_module = "decoders.syslog"
send_decode_failures = true
decoders_syslog = { }
```
- `run/output/debug.cfg:`

```
filename        = "heka_debug.lua"
message_matcher = "TRUE"
```

But syslog decoding always fail... I can see it in output :

```
root@node /etc/hindsight # hindsight main.cfg 7
1508164863963884644 [info] hindsight starting
1508164863974031089 [info] input.syslog_tcp starting
1508164863974290796 [info] analysis_plugins starting thread: 0
1508164863974409135 [debug] input_reader analysis0 opened file: /var/opt/hosting/data/hindsight/input/0.log offset: 5750
1508164863976650617 [info] output.debug starting
1508164863976704785 [debug] input_reader output.debug opened file: /var/opt/hosting/data/hindsight/input/0.log offset: 5750
1508164863976731206 [debug] input_reader output.debug opened file: /var/opt/hosting/data/hindsight/analysis/0.log

:Uuid: B68D6CDE-AB4D-4A6C-A65B-518842E55
:Timestamp: 2017-10-16T14:41:18.334463744Z
:Type: error
:Logger: input.syslog_tcp
:Severity: 7
:Payload: parse failed
:EnvVersion: <nil>
:Pid: <nil>
:Hostname: node008.bench.loghosts.m1.p.fti.net
:Fields:
```

I tried to adjust syslog template, message format type, and use standard `logger` cmd, or even set a bad formated template.. in all cases I have always the same result : "parse failed".
It's difficult to debug for me, when I add some "print" statements in `/usr/share/luasandbox/modules/lpeg/syslog.lua` I can't collect more informations.. all grammar related vars are in type "userdata".

Maybe everybody can reproduce the problem ... but it seems I'm wrong with something... or it's really a bug ?

Thanks a lot.

**Comment by trink** [comment]
You have to specify the proper template in your cfg; in this case ForwardFormat see https://rsyslog-5-8-6-doc.neocities.org/rsyslog_conf_templates.html. 
```
local template= "<%PRI%>%TIMESTAMP:::date-rfc3339% %HOSTNAME% %syslogtag:1:32%%msg:::sp-if-no-1st-sp%%msg%"
```
The default is TraditionalForwardFormat

**Comment by cvuillemez** [comment]
Template is still defined in `/usr/share/luasandbox/io_modules/decoders/syslog.lua` at line #38 (for Ubuntu, this file is provided by deb package lua-sandbox-extensions 0~git20161128-1) :
```local template  = read_config("template") or "<%PRI%>%TIMESTAMP% %HOSTNAME% %syslogtag:1:32%%msg:::sp-if-no-1st-sp%%msg%"```

So it's not the root cause.
Thanks.

**Comment by cvuillemez** [comment]
@trink can you re-open this issue ?

**Comment by trink** [comment]
??  I am unclear on what the perceived problem is (the above reference is to a PR that was not accepted).  The current packages and cfg work as expected as per https://mozilla-services.github.io/lua_sandbox_extensions/syslog/io_modules/decoders/syslog.html

**Comment by cvuillemez** [comment]
OK I pointed the mistake. My test message doesn't match the default template, and I test different templates format, but I put them in wrong place in configuration file:
```
filename = "tcp.lua"
address = "*"
decoder_module = "decoders.syslog"
send_decode_failures = true
decoders_syslog = { 
  template = "<%PRI%>%TIMESTAMP:::date-rfc3339% %HOSTNAME% %syslogtag:1:32%%msg:::sp-if-no-1st-sp%%msg%",
}
```

Template is well apllied with this config:

```
filename = "tcp.lua"
address = "*"
decoder_module = "decoders.syslog"
send_decode_failures = true
template = "<%PRI%>%TIMESTAMP:::date-rfc3339% %HOSTNAME% %syslogtag:1:32%%msg:::sp-if-no-1st-sp%%msg%"
```

So payload parsing is ok. Sorry for the mistake.

Note: the reference #38 is not a reference, i juste wanted to write "line 38" !
