### ISSUE TITLE
Kafka producer: add logging on delivery failure

### ISSUE THREAD

**Issue by cvuillemez** [mozilla-services/lua_sandbox_extensions#193]
When a message is rejected by librdkafka, [the failure counter](https://github.com/mozilla-services/lua_sandbox_extensions/blob/master/kafka/kafka.c#L92) is incremented but no message is logged.
Note: the callback function [rd_kafka_conf_set_dr_cb](https://github.com/mozilla-services/lua_sandbox_extensions/blob/master/kafka/kafka.c#L295) is deprecated.

**Comment by trink** [comment]
It will be pretty spammy (in your cases it would have been hundreds of thousands of log messages) but it will definitely help with debugging a bad configuration.  This should land in the first sprint of Q1 2018

**Comment by cvuillemez** [comment]
Yes but it can only print err at log_level = 7. Thanks.

**Comment by cvuillemez** [comment]
Trink, I think this issue is important to address cause when failures occur, the Kafka output plugin begins to malfunction (msg sent rate drop drastically.. and I don't know why... I just note it and it's a big problem with my heavy workload).
Thanks :)

**Comment by trink** [comment]
#204
