### ISSUE TITLE
Kafka producer: add topic configuration support

### ISSUE THREAD

**Issue by cvuillemez** [mozilla-services/lua_sandbox_extensions#194]
Some properties must be set on a topic level, cf [librdkafka doc](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md#topic-configuration-properties).
Actually [create_topic](https://github.com/mozilla-services/lua_sandbox_extensions/blob/master/kafka/sandboxes/heka/output/kafka.lua#L49) doesn't support it.

**Comment by trink** [comment]
Were you thinking a single default configuration or a specification per topic?

**Comment by cvuillemez** [comment]
A specification per topic would be better but in my case a default configuration is good enought.

**Comment by trink** [comment]
Ok, I will add per topic support with the ability to specify a default for unspecified topics.

**Comment by trink** [comment]
#204
