### ISSUE TITLE
lua sandbox ssl extensions

### ISSUE THREAD

**Issue by bbinet** [mozilla-services/lua_sandbox_extensions#20]
I'm in the process of building packages for lua sandbox extensions, and I noticed there are 2 ssl extensions, namely [ssl](https://github.com/mozilla-services/lua_sandbox_extensions/tree/master/ssl) and [openssl](https://github.com/mozilla-services/lua_sandbox_extensions/tree/master/openssl).

Is there a reason to provide both of them?
Which one should I preferably use to provide ssl support to the heka_tcp input/output sandboxes?

**Comment by trink** [comment]
They have different capabilities and some overlap.  For the use case above we use socket and luasec (ssl).
