### ISSUE TITLE
ssl module: bad libssl1.0.0 dependency on debian stetch

### ISSUE THREAD

**Issue by bbinet** [mozilla-services/lua_sandbox_extensions#202]
The ssl module adds a dependency on libssl1.0.0 (>= 1.0.1), see:
https://github.com/mozilla-services/lua_sandbox_extensions/blob/master/ssl/CMakeLists.txt.ssl#L20

But libssl1.0.0 is not available on Debian Stretch (stable) which only has libssl1.0.2 or libssl1.1.

Do you think it could be made compatible with both Debian Jessie and Stretch?

**Comment by trink** [comment]
I haven't found a good way to map the package name without doing something ugly like `dpkg -S libssl.so` then extracting the correct package name and adding it to the dependencies.  The other option is to leave the dependency off all together and the module will just fail on load if the lib is missing or mis-matched.

**Comment by bbinet** [comment]
What about this fix in #207 ?
