### ISSUE TITLE
Generalize table transformation into a heka message

### ISSUE THREAD

**Issue by trink** [mozilla-services/lua_sandbox_extensions#209]
Create a basic mapping function to convert and arbitrary table into a Heka message schema. See discussion https://github.com/mozilla-services/lua_sandbox_extensions/pull/146#discussion_r125105578

**Comment by trink** [comment]
@beorn- how about something like this https://github.com/mozilla-services/lua_sandbox_extensions/compare/dev...issue_209?expand=1

**Comment by beorn-** [comment]
It seems like a very good move. cleaner than what i have here.
