### ISSUE TITLE
Can't start heka_tcp output sandbox with ssl anymore

### ISSUE THREAD

**Issue by bbinet** [mozilla-services/lua_sandbox_extensions#23]
I've just upgraded my Hindsight setup to the latest version with the new ssl module from the new lua_sandbox_extensions repository, and when Hindsight is starting, it cannot start the heka_tcp output sandbox anymore and outputs the following error message:
```
1473094428480839671 [error] output.heka_tcp /usr/lib/luasandbox/io_modules/ssl.lua:11: attempt to index global 'table' (a nil value)
1473094428481049377 [error] output_plugins output.heka_tcp lsb_heka_create_output failed
1473094428481063853 [error] output_plugins output.heka_tcp create_output_plugin failed
```

The offending line in `/usr/lib/luasandbox/io_modules/ssl.lua` file is
```
local unpack  = table.unpack or unpack
```

I suppose this is due to the updated LuaSec version (the working one was the one from LuaDist: https://github.com/LuaDist/luasec)

Any idea how to fix this issue?

**Comment by trink** [comment]
yeah
```lua
require "table"
```
in heka_tcp.lua, I will merge the PR tomorrow

**Comment by bbinet** [comment]
I've tried to add `require "table"`in `heka_tcp.lua`, but I then have a new issue:
```
1473145311211815275 [error] output.heka_tcp /etc/hindsight/run/output/heka_tcp.lua:40: attempt to index global 'ssl' (a nil value)
1473145311211983318 [error] output_plugins output.heka_tcp lsb_heka_create_output failed
1473145311211995931 [error] output_plugins output.heka_tcp create_output_plugin failed
```
The offending line in `/etc/hindsight/run/output/heka_tcp.lua` is:
```
ssl_ctx = assert(ssl.newcontext(ssl_params))
```
So it seems the `require "ssl"` statement does not work...
