### ISSUE TITLE
geoip - add support for the ISP database

### ISSUE THREAD

**Issue by trink** [mozilla-services/lua_sandbox_extensions#232]

**Comment by champtar** [comment]
If you want geoip2 support (support all database type even custom ones)
https://github.com/champtar/lua_sandbox_extensions/commit/22508a23e80768f7a5a120f3c9daa6f3de028cd0

**Comment by trink** [comment]
@champtar Would you like to create a PR or should I just cherry pick it?

**Comment by trink** [comment]
@champtar, cherry-picked, thanks 9e643b7a5c7a959fdb31ef0d9748147659415a04

**Comment by champtar** [comment]
Thanks @trink (was going to do a PR this morning but you were faster ;) )
