### ISSUE TITLE
Improve how geoip module handles database being removed/replaced

### ISSUE THREAD

**Issue by ameihm0912** [mozilla-services/lua_sandbox_extensions#247]
The geoip module used for transforms seems to fail if the underlying GeoIP database file is removed/replaced during sandbox execution. It is not able to handle this scenario and requires a restart of the plugin using it, causing decoding failures until restarted.

This handling could likely be improved to take into account scenarios where the database is periodically updated.

**Comment by ameihm0912** [comment]
@trink @jasonthomas

**Comment by trink** [comment]
I suspect the new maxmind version would return ?? until the next hour when the db is re opened.  We can attempted a reopen based on the type of error returned.
