### ISSUE TITLE
rjson and snappy libc6 requirement

### ISSUE THREAD

**Issue by bbinet** [mozilla-services/lua_sandbox_extensions#26]
Both rjson and snappy requires libc6 version >= 2.14 on Debian: this requirement prevent installation on Debian Wheezy (oldstable) which is still in use.

Is there any reason for this restrictive requirement? Could we at least downgrade the requirement to 2.13 so that these plugins can be installed on Debian Wheezy?

See:
https://github.com/mozilla-services/lua_sandbox_extensions/blob/master/rjson/CMakeLists.txt#L21
https://github.com/mozilla-services/lua_sandbox_extensions/blob/master/snappy/CMakeLists.txt.snappy#L18

**Comment by trink** [comment]
It is based on what I have tested with.  If it is tested and works with the earlier version the restrictions can be relaxed.

**Comment by bbinet** [comment]
I can test the rjson extensions on wheezy (libc6 == 2.13), but I won't be able to test for snappy.

But why not relaxing the restrictions by default so that it is installable on any OS, and add back restrictions only if users have specific issues with old versions?
