### ISSUE TITLE
Add a syslog tcp input

### ISSUE THREAD

**Issue by sathieu** [mozilla-services/lua_sandbox_extensions#27]
Some products can send syslog via tcp, which is a bit more reliable.

**Comment by trink** [comment]
A 'help wanted' flag will be added to issues that would be accepted as a PR but Mozilla Services does not plan to work on.

**Comment by sathieu** [comment]
I'll try to work on this.

**Comment by trink** [comment]
The tcp input with a syslog decoder in my current sprint will address this.  I will close it after the merge of the sprint_oct17 branch.

**Comment by trink** [comment]
a27759cc316000af6ca4c05a998bfcb79d0ec480
