### ISSUE TITLE
CJSON module encode empty array to hash table

### ISSUE THREAD

**Issue by cvuillemez** [mozilla-services/lua_sandbox_extensions#302]
This is the behavior of cjson-lua, like explained [here](https://www.kyne.com.au/~mark/software/lua-cjson-manual.html#encode):

> Lua CJSON uses a heuristic to determine whether to encode a Lua table as a JSON array or an object. A Lua table with only positive integer keys of type number will be encoded as a JSON array. All other tables will be encoded as a JSON object.

It has lots of disadvantages, mostly when JSON payload must be injected in ElasticSearch: it raises mapping conflicts.</br>
[OpenResty ](https://github.com/openresty/lua-cjson) has forked the lua-cjson to fix the bug, which could be helpful for Hindsight/LUA sandboxes.

### Simple steps to reproduce it with Hindsight:

* input/tcp5555.cfg
```
filename = "tcp.lua"
decoder_module = "decoders.payload"
port = 5555
```
* analysis/json_parser.cfg
```
filename = "json_parser.lua"
message_matcher = "TRUE"
```
* analysis/json_parser.lua
```
local cjson = require "cjson"

function process_message()

  msg = {}
  msg.Payload = cjson.encode(cjson.decode(read_message("Payload")))
  inject_message(msg)
  return 0

end

function timer_event(ns)
end
```
* output/json_output.cfg
```
filename        = "heka_debug.lua"
message_matcher = "TRUE"
```

## Actual results
* OK
```
$ /usr/bin/hindsight /etc/hindsight/main.cfg &
[...]
$ echo '["foo"]' | nc -q0 localhost 5555
:Uuid: 729C321-B557-432F-A5B3-5AFA536DE3D9
:Timestamp: 2018-04-20T13:22:32.882180352Z
:Type: <nil>
:Logger: analysis.json_parser
:Severity: 7
:Payload: ["foo"]
:EnvVersion: <nil>
:Pid: <nil>
:Hostname: localhost
:Fields:
```
* KO
```
$ /usr/bin/hindsight /etc/hindsight/main.cfg &
[...]
$ echo '[]' | nc -q0 localhost 5555
:Uuid: 98DEE12F-AE19-4352-AAFE-402BA4A013E9
:Timestamp: 2018-04-20T13:22:10.880125952Z
:Type: <nil>
:Logger: analysis.json_parser
:Severity: 7
:Payload: {}
:EnvVersion: <nil>
:Pid: <nil>
:Hostname: localhost
:Fields:
```

**Comment by trink** [comment]
I am +1 for adding a cfg option to allow user selection as we have already made modifications to the core library https://github.com/mozilla-services/lua_sandbox_extensions/blob/master/cjson/index.md

**Comment by cvuillemez** [comment]
Yes it would be a good job !

**Comment by cvuillemez** [comment]
When this issue could be resolved ?

**Comment by trink** [comment]
It hasn't been scheduled yet.  I am currently working on anomaly detection and next week is our company all hands meeting (so it won't be this sprint).  It will be prioritized before the next sprint so I have an answer for you then.

**Comment by cvuillemez** [comment]
OK :)

**Comment by trink** [comment]
After looking into this there will be no configuration options.  The cjson encode/decode and lua sandbox state preservation will be updated to do proper round tripping.   If you manually create a lua table to output as JSON the tables can be initialized as follows.
```lua
hash = {}     -- empty hash
array = {nil} -- empty array
```

**Comment by cvuillemez** [comment]
Not possible. We receive messages from various sources, and we have no control on them. The applications which send us these messages are not LUA aware, they simply encode their data into JSON, so all empty arrays are represented by the string '[ ]'. I could discard the empty array in a analysis sandbox but it will be performed in full LUA, so too much consuming.

**Comment by trink** [comment]
CJSON will be modified to handle the specification above so cjson.decode -> cjson.encode it will round trip properly (no modification to the JSON input is necessary).  In addition you get proper state serialization/deserialization and you can manually construct Lua tables that would also cjson.encode properly (if you wanted to add an empty array)

**Comment by cvuillemez** [comment]
OK, it's more clear, it seems to be a good fix.
Thanks.

**Comment by trink** [comment]
#341

**Comment by cvuillemez** [comment]
Great !
I notice you applied changes in master branch for lua_sandbox project, but in dev branch for lua_sandbox_extensions. And maybe you forgot to increase the cjson module version ?

**Comment by trink** [comment]
Fixed, you are not be able to test this functional in the normal Lua package (it is only available into the sandbox version of Lua).  Here is how we test sandbox specific Lua https://github.com/mozilla-services/lua_sandbox_extensions/blob/dev/cjson/test_sandbox.c#L84

**Comment by trink** [comment]
These changes will be merged into master at the end of the sprint (the targeted 'release' is July 2).  As for the sandbox and hindsight merges to master they had to be done early to make our current CI setup happy.

**Comment by cvuillemez** [comment]
OK I 'll think using hindsight_cli to perform unit tests too.
Thank you for your explanations.

**Comment by rivertam** [comment]
Did this get reverted somehow? This isn't working for me with Redis 6.2.7; I'm having trouble figuring out what version the lua_sandbox_extensions would be.
