### ISSUE TITLE
changelog and "breaking changes" doc

### ISSUE THREAD

**Issue by cvuillemez** [mozilla-services/lua_sandbox_extensions#308]
It would be nice to have some clear changelog and "breaking changes" documentation, cause reading the commit logs can be tedious.
When upgrading the hindsight / luasandbox / luasandbox extensions stack, some changes expect users to do some rework (e.g. with deprecated geoip module). Thanks.

**Comment by cvuillemez** [comment]
Yes I encountered the change about "prune" plugin, but fixing it was easy :p.
You'are right, deprecate geoip didn't break anything but I found the missing build by chance.

**Comment by trink** [comment]
https://github.com/mozilla-services/hindsight/wiki/Change-Log
