### ISSUE TITLE
GCP Pub/Sub input plugin subscription_name issue

### ISSUE THREAD

**Issue by bbinet** [mozilla-services/lua_sandbox_extensions#333]
I have the following case:
I've created a first topic "test1" which I've subscribed from my GCP Pub/Sub input plugin with  config: 
```
topic = "test1"
subscription_name = "sn"
```
=> Everything is working correctly, I'm able to receive all messages coming to the topic "test1".

Then I've created a new topic named "test2", and I tried to update the topic name in the configuration of my GCP Pub/Sub input plugin (while keeping the same `subscription_name`):
```
topic = "test2"
subscription_name = "sn"
```
=> The GCP Pub/Sub input plugin was not able to receive any message from the new "test2" topic, and I could see on google cloud console that the new subscription named "sn" has not been created for the topic "test1".

But if I also change the `subscription_name` in the GCP Pub/Sub input plugin:
```
topic = "test2"
subscription_name = "sn_new"
```
=> Then everything is working well again.

So it seems the subscription name is not dependent on the topic and must be unique across all topics.
I guess this is a bug, but if not, I think this should be documented in the gcp input sandbox documentation.

What do you think?

**Comment by trink** [comment]
This is a a function of pub/sub subscriptions https://cloud.google.com/pubsub/docs/subscriber and not a bug with the sandbox.  If we remove the subscription creation in #332 the sandbox API can change to not even require topic avoiding some of the confusion.

**Comment by trink** [comment]
#355
