### ISSUE TITLE
Standard decoders should support transformations

### ISSUE THREAD

**Issue by ameihm0912** [mozilla-services/lua_sandbox_extensions#381]
Looks like with subdecoder util etc transformations are not possible, and they only work on grammars/printf/etc

It would be good if this could be extended to work with something like decoders.heka.table_to_fields

**Comment by trink** [comment]
Technically it is doable.  We have to trap all inject_message calls, insert the transformation in the wrapper and then call the real inject message. 

**Caveat**: this will only work with decoders calling inject_message with a table anything else would throw an error at this point as the APIs to support the transformation in the Heka Stream Reader or protobuf string are not exposed.

**Comment by ameihm0912** [comment]
https://github.com/mozilla-services/lua_sandbox_extensions/pull/388
