### ISSUE TITLE
Proposal: A Decoder configuration should support a verbose option

### ISSUE THREAD

**Issue by trink** [mozilla-services/lua_sandbox_extensions#386]
As the functionality and complexity has grown over time the terse option, on 
more complex setups, is difficult to setup/review. Would a verbose syntax be
useful :+1: :-1:

# function
A dedicated decoder function cannot be used as part of an ordered choice i.e. 
no array.
```lua
decoders_syslog = {...}
-- terse
decoder_module = "decoders.syslog"
-- verbose
decoder_module =  {
  type            = "function", 
  module          = "decoders.syslog"
}
```

# function (proposed #381 transformation)
```lua
decoders_syslog = {...}
-- terse
decoder_module = { {"decoders.syslog", {ssh_remote_ipaddr = "maxminddb.heka#add_geoip"}} } 
-- verbose
decoder_module =  {
  type            = "function", 
  module          = "decoders.syslog", 
  transformations = {
    ssh_remote_ipaddr = "maxminddb.heka#add_geoip"
  }
}
```

# printf
```lua
-- terse
decoder_module = { {{"%s:%lu: invalid line", "path", "linenum"}} }
-- verbose
decoder_module = { -- array is not necessary if we only have one
  type            = "printf", 
  format          = "%s:%lu: invalid line",
  args            = {"path", "linenum"},
  -- transformations = nil
}
    
```
# printf_messages
```lua
printf_messages = {
  "lpeg.openssh_portable",
}
-- terse
decoder_module = {"Accepted publickey for foobar from 192.168.1.1 port 4567 ssh2"}
-- verbose
decoder_module = {
  type            = "printf_messages", 
  message         = "Accepted publickey for foobar from 192.168.1.1 port 4567 ssh2", 
  -- transformations = nil
}
```

# printf_messages (transformation)
```lua
printf_messages = {
  "lpeg.openssh_portable",
}
-- terse
decoder_module = { {"Accepted publickey for foobar from 10.11.12.13 port 4242 ssh2", {ssh_remote_ipaddr = "maxminddb.heka#add_geoip"}} }
-- verbose
decoder_module = {
  type            = "printf_messages", 
  message         = "Accepted publickey for foobar from 192.168.1.1 port 4567 ssh2",
  transformations = {
    ssh_remote_ipaddr = "maxminddb.heka#add_geoip"
  }
}
```

# grammar
```lua
-- terse
decoder_module = "lpeg.logfmt"
-- verbose
decoder_module = {
  type            = "grammar", 
  module          = "lpeg.logfmt",
  -- grammar         = "grammar", -- grammar variable name optional default
  -- transformations = nil
}
```

# grammar (transformation)
```lua
-- terse
decoder_module = { {{"lpeg.logfmt"}, {ip = "maxminddb.heka#add_geoip"}} }
-- verbose
decoder_module = {
  type            = "grammar", 
  module          = "lpeg.logfmt",
  -- grammar         = "grammar",
  transformations = {
    ip = "maxminddb.heka#add_geoip"
  }
}
```

# grammar (match arguments)
```lua
-- terse
decoder_module = { {{"syslog_docs#demo", "www.example.com"}} }
-- verbose
decoder_module = {
  type            = "grammar", 
  module          = "syslog_docs",
  grammar         = "demo"
  args            = {"www.example.com"},
  -- transformations = nil
}
```

# grammar_builder
```lua
log_format = '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"'
-- terse
decoder_module = { {{"lpeg.common_log_format#build_nginx_grammar", log_format}} }
-- verbose
decoder_module = {
  type            = "grammar_builder", 
  module          = "lpeg.common_log_format",
  function        = "build_nginx_grammar"
  args            = {log_format},
  -- transformations = nil
}
```

# grammar_builder (transformation)
```lua
log_format = '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"'
-- terse
decoder_module = { {{"lpeg.common_log_format#build_nginx_grammar", log_format}, {remote_addr = "maxminddb.heka#add_geoip"}} }
-- verbose
decoder_module = {
  type            = "grammar_builder", 
  module          = "lpeg.common_log_format",
  function        = "build_nginx_grammar"
  args            = {log_format},  
  transformations = {
    remote_addr = "maxminddb.heka#add_geoip"
  }
}
```

# drop (ordered choice array)
```lua
-- terse
decoder_module = { {{"%s:%lu: invalid line", "path", "linenum"}}, "<<DROP>>" }
-- verbose
decoder_module = {
  {
    type            = "printf", 
    format          = "%s:%lu: invalid line",
    args            = {"path", "linenum"},
    -- transformations = nil
  },
  {type = "drop"} -- must be the last option
}
```

# fail (ordered choice array)
```lua
-- terse
decoder_module = { {{"%s:%lu: invalid line", "path", "linenum"}}, "<<FAIL>>" }
-- verbose
decoder_module = {
  {
    type            = "printf", 
    format          = "%s:%lu: invalid line",
    args            = {"path", "linenum"},
    -- transformations = nil
  },
  {type = "fail"} -- must be the last option
}
```

# allow mixed syntax?
```lua
printf_messages = {
  "lpeg.openssh_portable",
}
-- terse
decoder_module = {
  {{"%s:%lu: invalid line", "path", "linenum"}},
  "No user exists for uid 1023",
  {"Accepted publickey for foobar from 10.11.12.13 port 4242 ssh2", {ssh_remote_ipaddr = "maxminddb.heka#add_geoip"}},
  "<<DROP>>"
}
-- verbose
decoder_module = {
  {
    type            = "printf", 
    format          = "%s:%lu: invalid line",
    args            = {"path", "linenum"},
  },
  {
    type            = "printf_messages", 
    message         = "No user exists for uid 1023, 
  },
  {
    type            = "printf_messages", 
    message         = "Accepted publickey for foobar from 192.168.1.1 port 4567 ssh2",
    transformations = {
      ssh_remote_ipaddr = "maxminddb.heka#add_geoip"
    }
  },
  {
    type = "drop"
  }
}
-- mixed
decoder_module = {
  {{"%s:%lu: invalid line", "path", "linenum"}},
  "No user exists for uid 1023",
  {
    type            = "printf_messages", 
    message         = "Accepted publickey for foobar from 192.168.1.1 port 4567 ssh2",
    transformations = {
      ssh_remote_ipaddr = "maxminddb.heka#add_geoip"
    }
  },
  "<<DROP>>"
}    
```

**Comment by ameihm0912** [comment]
Would the intent be to support both syntax types, terse and verbose?

How would subdecoders work? Would we have a `subdecoders =` value?

This does seem slightly clearer to me, but I don't know if it is a large improvement on clarity.

**Comment by ameihm0912** [comment]
One other note here as well thinking about this, I think there are really two things that contribute to the clarity issues with the current syntax:

The first is the way the decoder configuration is handled differently depending on the type. For example, it can be a string, or a table. Where it's a table we can have an array, and various arbitrary array elements mean different things depending on it's use. This part of it is very confusing and hard to read unless you are comparing it to the documentation at the same time, but I think the verbose spec takes care of that.

The second issue is the way there are multiple means of decoding a message (printf, decoder, grammar, etc). Each of these have different parameters and are specified differently. This one I guess there is no easy way around. I think that is what makes the verbose specification still slightly unclear (e.g., there is no sort of uniformity/standard way of defining something).

**Comment by trink** [comment]
Yes, we will not break backward compatibility (and the two syntax will be functionally equivalent).

An individual decoder specification doesn't have the concept of a sub-decoder.  Sub-decoder is just a construct of a decoder module to group decoders in some appropriate way but it should have no impact on each individual specification.  I removed the term from the title to avoid this confusion.

If we don't come up with something that is a big win then supporting two syntax would be a very bad idea.
----
That is why this proposal exists; the meaning controlled by type inference requires one to be very familiar with the spec.

There is basically a fixed schema per type (as each has different requirements).  The only common fields are type, and transformations.  So we are trading a type based inference for a human readable schemas (each defining its own API).

**Comment by bbinet** [comment]
I'm still a newbie with the sub_decoder_util module but trying to learn and understand the way it works to use it with my own decoders.
I agree this is currently not very user friendly with the current "terse" configuration, as type inference is very confusing to me, and [the documentation](https://mozilla-services.github.io/lua_sandbox_extensions/lpeg/io_modules/lpeg/sub_decoder_util.html) is also limited (or a bit difficult to understand for me).

Actually, the parallel "verbose" and "terse" configurations that @trink has described in the description of this issue is helping me a lot to understand the current (terse) configuration.

So in my opinion, this "verbose" configuration would greatly improve the understanding of the sub_decoder_util.load_decoder function if there is no need for type inference anymore.
Also, I think the "verbose" configuration would also be more easy to document than the "terse" one which is always dependent of the type.

**Comment by trink** [comment]
@bbinet for real world examples see:
http://mozilla-services.github.io/hindsight/tutorials/using_decoders_with_input_plugins.html
http://mozilla-services.github.io/hindsight/tutorials/cookbooks.html

**Comment by bbinet** [comment]
@trink these tutorials are useful, thank you.

It would also be interesting to give an example with a different decoder than the "decoders.syslog" and which would also support multiple sub-decoders (all examples in http://mozilla-services.github.io/hindsight/tutorials/using_decoders_with_input_plugins.html are based on "decoders.syslog")
Or it could be useful to have a tutorial explaining how to create a custom decoder that can support  multiple sub-decoders.
