### ISSUE TITLE
Document `enable_delta` argument to `circular_buffer.new`

### ISSUE THREAD

**Issue by xbonez** [mozilla-services/lua_sandbox_extensions#40]
If one wants to output `cbufd` format, it seems that a fourth argument set to `true` needs to be passed to `circular_buffer.new()`.

This is not documented. I was able to realize this by looking at the [`unique_items.lua`](https://github.com/mozilla-services/heka/blob/34e00a8c33dc21b8ad40b6d239faba6e8fc18ad4/sandbox/lua/filters/unique_items.lua) filter.

**Comment by trink** [comment]
The 4th parameter was removed before the circular_buffer 1.0 release and Heka has not been upgraded to use the the 1.0+ lua_sandbox or modules.  The documentation for the version Heka uses is here: https://github.com/mozilla-services/lua_circular_buffer/blob/bb6dd9f88f148813315b5a660b7e2ba47f958b31/README.md
