### ISSUE TITLE
Pubsub consumer limited to receiving 4MB messages by default GRPC settings

### ISSUE THREAD

**Issue by whd** [mozilla-services/lua_sandbox_extensions#408]
I'm seeing for large messages like telemetry:
 
    projects/PROJECT/subscriptions/SUBSCRIPTION pull error      8       Received message larger than max (5131598 vs. 4194304)

It looks like we can set this to unlimited or possibly max message size.

**Comment by whd** [comment]
As a note, as I was tuning parameters, decreasing the batch_size to 100 for my particular configuration and data has caused these messages to no longer appear.

**Comment by trink** [comment]
It looks like we would have to set it to unlimited OR max message size * batch size; so that could be up to a 10GiB request. I will run some tests.
