### ISSUE TITLE
taskcluster - update mozilla_com table with people.m.o data

### ISSUE THREAD

**Issue by srfraser** [mozilla-services/lua_sandbox_extensions#489]
We have a table, taskclusteretl.mozilla_com containing an import of the org chart for use in the cost dashboards.

I don't know if this is currently updated on a schedule, but we should ensure it is.
We should also investigate importing people's other email identities and github usernames, as a portion of our workload is submitted by people who are in the org chart, but don't use their 'work' address. If it's all in the table we could ensure managers get an accurate representation of their team. 

Whether this means the owner email field becomes an array, or there are duplicate rows for a person, I don't know.

**Comment by trink** [comment]
https://github.com/mozilla-services/lua_sandbox_extensions/blob/master/taskcluster/bin/realorg.lua

realorg.json is the imported secret see: https://bugzilla.mozilla.org/show_bug.cgi?id=1579068

**Comment by trink** [comment]
An automated solution should be based on this: https://github.com/mozilla-iam/cis/issues/402

**Comment by trink** [comment]
This has been deployed
