### ISSUE TITLE
Build faild on CentOS

### ISSUE THREAD

**Issue by liuyangc3** [mozilla-services/lua_sandbox_extensions#54]
error says can not find parquet-cpp
```
CMake Error at parquet/CMakeLists.txt:9 (find_package):
  Could not find a package configuration file provided by "parquet-cpp" with
  any of the following names:

    parquet-cppConfig.cmake
    parquet-cpp-config.cmake

  Add the installation prefix of "parquet-cpp" to CMAKE_PREFIX_PATH or set
  "parquet-cpp_DIR" to a directory containing one of the above files.  If
  "parquet-cpp" provides a separate development package or SDK, be sure it
  has been installed.


CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBRTKAFKA_LIBRARY
    linked by target "kafka" in directory /opt/lua_sandbox_extensions/kafka

-- Configuring incomplete, errors occurred!
See also "/opt/lua_sandbox_extensions/release/CMakeFiles/CMakeOutput.log".
```
but I did install the parquet-cpp with following steps in readme.md of https://github.com/apache/parquet-cpp
```
[root@ansible release]# ll /usr/local/lib/libparquet.so
-rwxr-xr-x 1 root root 14580809 Dec 15 17:39 /usr/local/lib/libparquet.so
```

**Comment by trink** [comment]
The parquet-cpp rpm has to be installed.  The version that builds a proper package is here: https://github.com/trink/parquet-cpp/tree/cpack_support

**Comment by liuyangc3** [comment]
I checkouted cpack_support branch and cpacked a rpm
![image](https://cloud.githubusercontent.com/assets/6705844/21250944/1f4ac140-c384-11e6-868f-79db3b663019.png)

but got a new  error
![image](https://cloud.githubusercontent.com/assets/6705844/21250977/8b40d2a4-c384-11e6-935d-47948ff2c2ab.png)

**Comment by sathieu** [comment]
As said in the README, only build the modules you need.

So unless you need kafka, disable it.

**Comment by liuyangc3** [comment]
@sathieu yes, I read the README, but I just want to test each module  **can be** build

**Comment by trink** [comment]
Then you need to install librdkafka as well.  FYI: I fixed the typo in the VAR name, it used consistently so it is not an issue, but it will be in my next set of commits.

**Comment by liuyangc3** [comment]
appreciate it @trink
