### ISSUE TITLE
lfs - create a tail -f/-F input plugin

### ISSUE THREAD

**Issue by trink** [mozilla-services/lua_sandbox_extensions#72]

**Comment by champtar** [comment]
Hi @trink,
Do you plan to support saving offset read so far (like heka  LogstreamerInput journal_directory)?
Any time frame?

Thanks

**Comment by trink** [comment]
Yes, it will have check pointing like the basic file input https://github.com/mozilla-services/lua_sandbox_extensions/blob/master/heka/sandboxes/heka/input/file.lua and is scheduled for the next sprint.

**Comment by champtar** [comment]
Perfect, thanks!

**Comment by trink** [comment]
Closed by 753bf3c0a94ca71c590d8d7b65072fbd12657f82
