### ISSUE TITLE
Third Party Sandbox Extensions repo layout

### ISSUE THREAD

**Issue by champtar** [mozilla-services/lua_sandbox_extensions#73]
Hi @trink,

I know you added this wiki page a while ago:
https://github.com/mozilla-services/lua_sandbox_extensions/wiki/Third-Party-Sandbox-Extensions

I'm just wondering what do you prefer:
1) copy top level CMakeLists.txt into the third party repo (not ideal)
2) improve this CMakeLists.txt to be able to reference just the external extension at configure time, maybe something like ```-DEXTERNAL_EXT_<ext-name>=<ext-path>```

I'm now using the original project, not a fork of a fork https://github.com/champtar/lua_sandbox_extensions/commit/68fdb46a325d375e869d9c52588b289059a01ba2
original PR: #50

Regards

**Comment by trink** [comment]
The top level CMakeLists.txt is not what you want for a standalone luasandbox-ext repo. It would be closer to a modified copy of the sandbox_modules.cmake and would be unique to the new repo with no dependencies on the lua_sandbox_extension repo.

**Comment by trink** [comment]
The repo layout will vary, here is an example of a C module (creating three packages, a C library and lua51/luasandbox bindings) https://github.com/trink/streaming_algorithms
